#!/bin/sh

# Copyright 2020-2022, 2024, 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this script to regenerate the Bazel output in compile.org.

set -eu

org="$(bazel --quiet info workspace)/testdata/compile.org" || exit
dir="$(mktemp -d)" || exit

# Set up a basic repository layout in the temporary directory.
cp -- "${org:?}" "${dir:?}/.tangle.org" || exit
emacs --quick --batch --visit="${dir:?}/.tangle.org" \
  --funcall='org-babel-tangle' || exit

(
  set -eu
  # We explicitly compile with the current directory set to a subdirectory to
  # ensure that repository-relative filenames still work as expected.
  cd "${dir:?}/package" || exit
  # Invert the exit status of “bazel build” because we expect it to fail.  We
  # can’t use --quiet here because that would also suppress the deprecation
  # warning.
  ! bazel --nohome_rc build --attempt_to_print_relative_paths --noshow_progress --noshow_loading_progress //... 2>&1
) || exit

rm -r -f -- "${dir}"
