#!/bin/bash

# Copyright 2021-2022, 2024, 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this script to regenerate the Bazel output and coverage file in
# coverage.org.

set -eu

workspace="$(bazel --quiet info workspace)" || exit
testdata="${workspace:?}/testdata"
org="${testdata:?}/coverage.org"

dir="$(mktemp -d)" || exit
trap 'rm -r -f -- "${dir}"' EXIT

# Canonicalize the directory so that the textual replacement below doesn’t
# choke on symbolic links.
dir="$(realpath -- "${dir:?}")" || exit

# Set up a basic repository layout in the temporary directory.
cp -- "${org:?}" "${dir:?}/.tangle.org" || exit
emacs --quick --batch --visit="${dir:?}/.tangle.org" \
  --funcall='org-babel-tangle' || exit
rm -- "${dir:?}/.tangle.org" || exit

# Remove tangled “bazel-out” directory containing the previous coverage data.
# This would interfere with the Bazel run below.
rm -r -- "${dir:?}/bazel-out"

testlogs="$(cd "${dir:?}" && bazel --nohome_rc --quiet info bazel-testlogs)"

# We explicitly compile with the current directory set to a subdirectory to
# ensure that repository-relative filenames still work as expected.
out="$(cd "${dir:?}/src" && bazel --nohome_rc --quiet coverage --attempt_to_print_relative_paths //... 2>&1)"

# Parse output to find location of coverage.dat.  The output should be
# relatively stable, cf. https://bazel.build/run/scripts#parsing-output.
pattern=$'\n''  (/.+/coverage\.dat)'$'\n'
[[ "${out:?}" =~ ${pattern:?} ]] || exit
dat="${BASH_REMATCH[1]}"

# Replace test log directory in the output with a fixed value.  This gets rid
# of the arbitrary build configuration directory.
out="${out//${testlogs}/%ROOTDIR%/bazel-out/k8-fastbuild/testlogs}"

# Generate fake tangled files with links so we can use ‘org-babel-detangle’.
echo '# [[file:detangle.org::bazel.out][bazel.out]]' > "${dir:?}/bazel.out"
echo "${out:?}" >> "${dir:?}/bazel.out"
echo '# bazel.out ends here' >> "${dir:?}/bazel.out"

echo '# [[file:detangle.org::coverage.dat][coverage.dat]]' > "${dir:?}/coverage.dat"
cat "${dat:?}" >> "${dir:?}/coverage.dat"
echo '# coverage.dat ends here' >> "${dir:?}/coverage.dat"

cp -- "${org:?}" "${dir:?}/detangle.org" || exit
emacs --quick --batch --load='ob-tangle' --visit="${dir:?}/bazel.out" \
  --eval='(setq org-src-content-indentation 0)' --funcall='org-babel-detangle' \
  --eval='(save-some-buffers t)' || exit
emacs --quick --batch --load='ob-tangle' --visit="${dir:?}/coverage.dat" \
  --eval='(setq org-src-content-indentation 0)' --funcall='org-babel-detangle' \
  --eval='(save-some-buffers t)' || exit
cp -- "${dir:?}/detangle.org" "${org:?}" || exit

echo 'Successfully refreshed coverage.org.'
