#!/bin/bash

# Copyright 2020-2022, 2024, 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this script to regenerate the Bazel output in fix-visibility.org.

set -eu

workspace="$(bazel --quiet info workspace)" || exit
testdata="${workspace:?}/testdata"
org="${testdata:?}/fix-visibility.org"

dir="$(mktemp -d)" || exit
trap 'rm -r -f -- "${dir}"' EXIT

# Canonicalize the directory so that the textual replacement below doesn’t
# choke on symbolic links.
dir="$(realpath -- "${dir:?}")" || exit

# Set up a basic repository layout in the temporary directory.
cp -- "${org:?}" "${dir:?}/.tangle.org" || exit
emacs --quick --batch --visit="${dir:?}/.tangle.org" \
  --funcall='org-babel-tangle' || exit
rm -- "${dir:?}/.tangle.org" || exit


(
  # Generate fake tangled file with links so we can use ‘org-babel-detangle’.
  echo '# [[file:detangle.org::bazel.out][bazel.out]]'
  # We explicitly compile with the current directory set to a subdirectory to
  # ensure that repository-relative filenames still work as expected.
  cd "${dir:?}/lib" || exit
  # Invert the exit status of “bazel build” because we expect it to fail.
  ! bazel --nohome_rc --quiet build --attempt_to_print_relative_paths --nobuild //... 2>&1
  echo '# bazel.out ends here'
) > "${dir:?}/bazel.out" || exit

cp -- "${org:?}" "${dir:?}/detangle.org" || exit
emacs --quick --batch --load='ob-tangle' --visit="${dir:?}/bazel.out" \
  --eval='(setq org-src-content-indentation 0)' --funcall='org-babel-detangle' \
  --eval='(save-some-buffers t)' || exit
cp -- "${dir:?}/detangle.org" "${org:?}" || exit

echo 'Successfully refreshed fix-visibility.org'
